version: '3.8'

services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      MONGO_DB_NAME: ${MONGO_DB_NAME}
      MONGO_URL: ${MONGO_URL}
      PORT: ${PORT}
    volumes:
      - .:/app
      - /app/node_modules
